image: node:8.7.0

stages:
  - test
  - deploy

test-backend:
  stage: test
  cache:
    paths:
    - ts-backend/node_modules/
  script:
  - cd ts-backend
  - npm install
  - npm test

pages:
  stage: deploy
  cache:
    paths:
    - ts-frontend/node_modules/
  script:
  - cd ts-frontend
  - npm install
  - npm run build
  - mkdir public
  - mv build/* public/
  - mkdir public/src
  - cp src/styles.css public/src/styles.css
  artifacts:
    paths:
    - public
  only:
  - master