image: node:8.7.0

pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
  - npm install
  - npm run build
  - mkdir public
  - mv build public/
  - cp index.html public/
  artifacts:
    paths:
    - public
  only:
  - master