.PHONY: run-api
run-api:
	go run main.go

.PHONY: normalize-dictionary
normalize-dictionary:
	go run cli/main.go --input=../../dictionaries-new/portuguese-300k.txt --output=../../dictionaries-new/portuguese-sorted.txt
