import {RequestStatus} from 'src/api';

export default {
    "queryStatus": RequestStatus.loading,
    "query":"johannes von plato",
    "cleanedQuery":"johannesvonplato",
    "dictionaries":[
       {
          "id":"eng-us-3k",
          "name":"English 3k"
       },
       {
          "id":"eng-us-10k",
          "name":"English 10k"
       },
       {
          "id":"eng-us-50k",
          "name":"English 50k"
       },
       {
          "id":"eng-countries",
          "name":"English Countries"
       },
       {
          "id":"de-3k",
          "name":"German 3k"
       },
       {
          "id":"de-10k",
          "name":"German 10k"
       },
       {
          "id":"de-50k",
          "name":"German 50k"
       },
       {
          "id":"de-countries",
          "name":"German Countries"
       },
       {
          "id":"famous-people",
          "name":"Famous People"
       }
    ],
    "selectedDictionaries":"eng-us-3k",
    "subanagrams":[
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "n0",
                "o0",
                "o1",
                "p0",
                "s0",
                "t0"
             ],
             "word":"teaspoon"
          },
          "index":0
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "n0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"honest"
          },
          "index":1
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "n0",
                "p0",
                "t0"
             ],
             "word":"planet"
          },
          "index":2
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "n0",
                "o0"
             ],
             "word":"alone"
          },
          "index":3
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "l0",
                "o0",
                "t0"
             ],
             "word":"hotel"
          },
          "index":4
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "s0",
                "t0"
             ],
             "word":"least"
          },
          "index":5
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "o0",
                "o1",
                "s0"
             ],
             "word":"loose"
          },
          "index":6
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "n0",
                "o0",
                "v0"
             ],
             "word":"novel"
          },
          "index":7
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "n0",
                "p0"
             ],
             "word":"panel"
          },
          "index":8
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "h0",
                "p0",
                "s0"
             ],
             "word":"phase"
          },
          "index":9
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "n0",
                "o0",
                "p0"
             ],
             "word":"phone"
          },
          "index":10
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "o1",
                "p0",
                "t0"
             ],
             "word":"photo"
          },
          "index":11
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "n0",
                "p0"
             ],
             "word":"plane"
          },
          "index":12
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "n0",
                "p0",
                "t0"
             ],
             "word":"plant"
          },
          "index":13
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "p0",
                "t0"
             ],
             "word":"plate"
          },
          "index":14
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "h0",
                "p0",
                "s0"
             ],
             "word":"shape"
          },
          "index":15
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "o1",
                "s0",
                "t0"
             ],
             "word":"shoot"
          },
          "index":16
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "s0",
                "v0"
             ],
             "word":"slave"
          },
          "index":17
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "o0",
                "s0",
                "v0"
             ],
             "word":"solve"
          },
          "index":18
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "s0",
                "t0"
             ],
             "word":"steal"
          },
          "index":19
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"stone"
          },
          "index":20
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"those"
          },
          "index":21
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "o0",
                "s0"
             ],
             "word":"also"
          },
          "index":22
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "s0",
                "t0"
             ],
             "word":"east"
          },
          "index":23
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "h0",
                "t0"
             ],
             "word":"hate"
          },
          "index":24
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "h0",
                "v0"
             ],
             "word":"have"
          },
          "index":25
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "h0",
                "t0"
             ],
             "word":"heat"
          },
          "index":26
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "l0",
                "p0"
             ],
             "word":"help"
          },
          "index":27
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "l0",
                "o0"
             ],
             "word":"hole"
          },
          "index":28
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "o0",
                "p0"
             ],
             "word":"hope"
          },
          "index":29
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"host"
          },
          "index":30
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "s0",
                "t0"
             ],
             "word":"last"
          },
          "index":31
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "t0"
             ],
             "word":"late"
          },
          "index":32
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "n0"
             ],
             "word":"lean"
          },
          "index":33
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "n0",
                "o0"
             ],
             "word":"loan"
          },
          "index":34
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "o0",
                "s0"
             ],
             "word":"lose"
          },
          "index":35
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"lost"
          },
          "index":36
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"lots"
          },
          "index":37
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "o0",
                "v0"
             ],
             "word":"love"
          },
          "index":38
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "n1",
                "o0"
             ],
             "word":"none"
          },
          "index":39
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "s0"
             ],
             "word":"nose"
          },
          "index":40
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "t0"
             ],
             "word":"note"
          },
          "index":41
       },
       {
          "word":{
             "set":[
                "n0",
                "o0",
                "o1",
                "t0"
             ],
             "word":"onto"
          },
          "index":42
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "p0"
             ],
             "word":"open"
          },
          "index":43
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "v0"
             ],
             "word":"oven"
          },
          "index":44
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "p0"
             ],
             "word":"pale"
          },
          "index":45
       },
       {
          "word":{
             "set":[
                "a0",
                "n0",
                "p0",
                "t0"
             ],
             "word":"pant"
          },
          "index":46
       },
       {
          "word":{
             "set":[
                "a0",
                "p0",
                "s0",
                "t0"
             ],
             "word":"past"
          },
          "index":47
       },
       {
          "word":{
             "set":[
                "a0",
                "h0",
                "p0",
                "t0"
             ],
             "word":"path"
          },
          "index":48
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "n0",
                "p0"
             ],
             "word":"plan"
          },
          "index":49
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "p0",
                "t0"
             ],
             "word":"plot"
          },
          "index":50
       },
       {
          "word":{
             "set":[
                "e0",
                "o0",
                "p0",
                "t0"
             ],
             "word":"poet"
          },
          "index":51
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "o0",
                "p0"
             ],
             "word":"pole"
          },
          "index":52
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "o1",
                "p0"
             ],
             "word":"pool"
          },
          "index":53
       },
       {
          "word":{
             "set":[
                "e0",
                "o0",
                "p0",
                "s0"
             ],
             "word":"pose"
          },
          "index":54
       },
       {
          "word":{
             "set":[
                "o0",
                "p0",
                "s0",
                "t0"
             ],
             "word":"post"
          },
          "index":55
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "s0"
             ],
             "word":"sale"
          },
          "index":56
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "s0",
                "t0"
             ],
             "word":"salt"
          },
          "index":57
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "s0",
                "v0"
             ],
             "word":"save"
          },
          "index":58
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "s0",
                "t0"
             ],
             "word":"seat"
          },
          "index":59
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "o0",
                "s0"
             ],
             "word":"shoe"
          },
          "index":60
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "p0",
                "s0"
             ],
             "word":"shop"
          },
          "index":61
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "s0",
                "t0"
             ],
             "word":"shot"
          },
          "index":62
       },
       {
          "word":{
             "set":[
                "a0",
                "n0",
                "p0",
                "s0"
             ],
             "word":"snap"
          },
          "index":63
       },
       {
          "word":{
             "set":[
                "n0",
                "o0",
                "o1",
                "s0"
             ],
             "word":"soon"
          },
          "index":64
       },
       {
          "word":{
             "set":[
                "o0",
                "p0",
                "s0",
                "t0"
             ],
             "word":"spot"
          },
          "index":65
       },
       {
          "word":{
             "set":[
                "e0",
                "p0",
                "s0",
                "t0"
             ],
             "word":"step"
          },
          "index":66
       },
       {
          "word":{
             "set":[
                "o0",
                "p0",
                "s0",
                "t0"
             ],
             "word":"stop"
          },
          "index":67
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "l0",
                "t0"
             ],
             "word":"tale"
          },
          "index":68
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "p0",
                "t0"
             ],
             "word":"tape"
          },
          "index":69
       },
       {
          "word":{
             "set":[
                "a0",
                "h0",
                "n0",
                "t0"
             ],
             "word":"than"
          },
          "index":70
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "n0",
                "t0"
             ],
             "word":"then"
          },
          "index":71
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0",
                "t0"
             ],
             "word":"tone"
          },
          "index":72
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "o1",
                "t0"
             ],
             "word":"tool"
          },
          "index":73
       },
       {
          "word":{
             "set":[
                "a0",
                "s0",
                "t0",
                "v0"
             ],
             "word":"vast"
          },
          "index":74
       },
       {
          "word":{
             "set":[
                "e0",
                "o0",
                "t0",
                "v0"
             ],
             "word":"vote"
          },
          "index":75
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "t0"
             ],
             "word":"eat"
          },
          "index":76
       },
       {
          "word":{
             "set":[
                "a0",
                "h0",
                "t0"
             ],
             "word":"hat"
          },
          "index":77
       },
       {
          "word":{
             "set":[
                "h0",
                "o0",
                "t0"
             ],
             "word":"hot"
          },
          "index":78
       },
       {
          "word":{
             "set":[
                "e0",
                "j0",
                "t0"
             ],
             "word":"jet"
          },
          "index":79
       },
       {
          "word":{
             "set":[
                "a0",
                "l0",
                "p0"
             ],
             "word":"lap"
          },
          "index":80
       },
       {
          "word":{
             "set":[
                "e0",
                "l0",
                "t0"
             ],
             "word":"let"
          },
          "index":81
       },
       {
          "word":{
             "set":[
                "l0",
                "o0",
                "t0"
             ],
             "word":"lot"
          },
          "index":82
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "t0"
             ],
             "word":"net"
          },
          "index":83
       },
       {
          "word":{
             "set":[
                "n0",
                "o0",
                "t0"
             ],
             "word":"not"
          },
          "index":84
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "o0"
             ],
             "word":"one"
          },
          "index":85
       },
       {
          "word":{
             "set":[
                "a0",
                "n0",
                "p0"
             ],
             "word":"pan"
          },
          "index":86
       },
       {
          "word":{
             "set":[
                "e0",
                "p0",
                "t0"
             ],
             "word":"pet"
          },
          "index":87
       },
       {
          "word":{
             "set":[
                "o0",
                "p0",
                "t0"
             ],
             "word":"pot"
          },
          "index":88
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "s0"
             ],
             "word":"sea"
          },
          "index":89
       },
       {
          "word":{
             "set":[
                "e0",
                "s0",
                "t0"
             ],
             "word":"set"
          },
          "index":90
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "s0"
             ],
             "word":"she"
          },
          "index":91
       },
       {
          "word":{
             "set":[
                "n0",
                "o0",
                "s0"
             ],
             "word":"son"
          },
          "index":92
       },
       {
          "word":{
             "set":[
                "a0",
                "p0",
                "t0"
             ],
             "word":"tap"
          },
          "index":93
       },
       {
          "word":{
             "set":[
                "a0",
                "e0",
                "t0"
             ],
             "word":"tea"
          },
          "index":94
       },
       {
          "word":{
             "set":[
                "e0",
                "n0",
                "t0"
             ],
             "word":"ten"
          },
          "index":95
       },
       {
          "word":{
             "set":[
                "e0",
                "h0",
                "t0"
             ],
             "word":"the"
          },
          "index":96
       },
       {
          "word":{
             "set":[
                "e0",
                "o0",
                "t0"
             ],
             "word":"toe"
          },
          "index":97
       },
       {
          "word":{
             "set":[
                "o0",
                "o1",
                "t0"
             ],
             "word":"too"
          },
          "index":98
       },
       {
          "word":{
             "set":[
                "o0",
                "p0",
                "t0"
             ],
             "word":"top"
          },
          "index":99
       },
       {
          "word":{
             "set":[
                "a0",
                "h0"
             ],
             "word":"ah"
          },
          "index":100
       },
       {
          "word":{
             "set":[
                "a0",
                "s0"
             ],
             "word":"as"
          },
          "index":101
       },
       {
          "word":{
             "set":[
                "a0",
                "t0"
             ],
             "word":"at"
          },
          "index":102
       },
       {
          "word":{
             "set":[
                "e0",
                "h0"
             ],
             "word":"he"
          },
          "index":103
       },
       {
          "word":{
             "set":[
                "n0",
                "o0"
             ],
             "word":"no"
          },
          "index":104
       },
       {
          "word":{
             "set":[
                "h0",
                "o0"
             ],
             "word":"oh"
          },
          "index":105
       },
       {
          "word":{
             "set":[
                "n0",
                "o0"
             ],
             "word":"on"
          },
          "index":106
       },
       {
          "word":{
             "set":[
                "o0",
                "s0"
             ],
             "word":"so"
          },
          "index":107
       },
       {
          "word":{
             "set":[
                "o0",
                "t0"
             ],
             "word":"to"
          },
          "index":108
       },
       {
          "word":{
             "set":[
                "t0",
                "v0"
             ],
             "word":"tv"
          },
          "index":109
       },
       {
          "word":{
             "set":[
                "s0",
                "v0"
             ],
             "word":"vs"
          },
          "index":110
       },
       {
          "word":{
             "set":[
                "a0"
             ],
             "word":"a"
          },
          "index":111
       }
    ],
    "anagramIteratorState":{
       "counter":37602,
       "numberOfPossibilitiesChecked":32836,
       "unsolvedSubanagrams":[
 
       ],
       "solvedSubanagrams":[
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          43,
          44,
          45,
          46,
          47,
          48,
          49,
          50,
          51,
          52,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63,
          64,
          65,
          66,
          67,
          68,
          69,
          70,
          71,
          72,
          73,
          74,
          75,
          76,
          77,
          78,
          79,
          80,
          81,
          82,
          83,
          84,
          85,
          86,
          87,
          88,
          89,
          90,
          91,
          92,
          93,
          94,
          95,
          96,
          97,
          98,
          99,
          100,
          101,
          102,
          103,
          104,
          105,
          106,
          107,
          108,
          109,
          110
       ],
       "currentSubanagrams":[
          111
       ],
       "solutions":[
          [
             34,
             79,
             86,
             105,
             106,
             110
          ],
          [
             34,
             79,
             86,
             104,
             105,
             110
          ],
          [
             49,
             79,
             105,
             106,
             106,
             110,
             111
          ],
          [
             49,
             79,
             104,
             105,
             106,
             110,
             111
          ],
          [
             49,
             79,
             104,
             104,
             105,
             110,
             111
          ],
          [
             79,
             80,
             100,
             106,
             106,
             106,
             110
          ],
          [
             79,
             80,
             100,
             104,
             106,
             106,
             110
          ],
          [
             79,
             80,
             100,
             104,
             104,
             106,
             110
          ],
          [
             79,
             80,
             100,
             104,
             104,
             104,
             110
          ]
       ]
    }
 };